import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { DMMF } from '@prisma/generator-helper';
import { ensureDir } from '../utils/paths.js';

/**
 * Write DMMF as a JSON file
 */
export function writeDmmfJson(outputDir: string, dmmf: DMMF.Document): string {
  const dmmfDir = join(outputDir, 'dmmf');
  ensureDir(dmmfDir);

  const jsonPath = join(dmmfDir, 'dmmf.json');
  writeFileSync(jsonPath, JSON.stringify(dmmf, null, 2), 'utf-8');

  return jsonPath;
}

/**
 * Write DMMF as a TypeScript module
 */
export function writeDmmfTs(outputDir: string, dmmf: DMMF.Document): string {
  const dmmfDir = join(outputDir, 'dmmf');
  ensureDir(dmmfDir);

  const tsContent = `// Generated by @paljs/generator - DO NOT EDIT
import type { DMMF } from '@prisma/generator-helper';

export const dmmf: DMMF.Document = ${JSON.stringify(dmmf, null, 2)} as const;

export default dmmf;
`;

  const tsPath = join(dmmfDir, 'index.ts');
  writeFileSync(tsPath, tsContent, 'utf-8');

  return tsPath;
}

/**
 * Write both JSON and TypeScript DMMF files
 */
export function writeDmmf(
  outputDir: string,
  dmmf: DMMF.Document,
): {
  jsonPath: string;
  tsPath: string;
} {
  return {
    jsonPath: writeDmmfJson(outputDir, dmmf),
    tsPath: writeDmmfTs(outputDir, dmmf),
  };
}
