import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import type { GeneratorManifest, GeneratorOptions } from '@prisma/generator-helper';
const require = createRequire(import.meta.url);
const { generatorHandler } = require('@prisma/generator-helper');
import { dirname, resolve } from 'node:path';
import { type ResolvedConfig, findConfigPath, loadConfig } from './config/index.js';
import { ensureDir } from './utils/paths.js';
import { writeAdmin } from './writers/admin/index.js';
import { writeDmmf } from './writers/dmmf.js';
import { writeGraphQL } from './writers/graphql/index.js';
import { writeNexus } from './writers/nexus/index.js';
import { writeTypes } from './writers/types.js';

const GENERATOR_NAME = 'paljs-generator';

// Read version from package.json
const __dirname = dirname(fileURLToPath(import.meta.url));
const packageJson = JSON.parse(readFileSync(resolve(__dirname, '../package.json'), 'utf-8'));
const GENERATOR_VERSION = packageJson.version;

/**
 * Generator manifest - provides metadata about the generator
 */
function onManifest(): GeneratorManifest {
  return {
    defaultOutput: './generated/paljs',
    prettyName: 'PalJS Generator',
    version: GENERATOR_VERSION,
  };
}

/**
 * Main generator function - called during prisma generate
 */
async function onGenerate(options: GeneratorOptions): Promise<void> {
  const { generator, dmmf, schemaPath } = options;

  // Get output directory
  const outputDir = generator.output?.value;
  if (!outputDir) {
    throw new Error('Output directory is required. Add `output = "./generated/paljs"` to your generator block.');
  }

  // Ensure output directory exists
  ensureDir(outputDir);

  // Find and load configuration
  const schemaDir = dirname(schemaPath);
  const configPathFromGenerator = generator.config?.config as string | undefined;

  let configPath: string | null = null;

  if (configPathFromGenerator) {
    // Config path specified in generator block
    configPath = resolve(schemaDir, configPathFromGenerator);
  } else {
    // Search for config in schema directory first, then project root
    configPath = findConfigPath(schemaDir);
    if (!configPath) {
      // Try parent directory (project root) if schema is in a subdirectory like prisma/
      const projectRoot = dirname(schemaDir);
      configPath = findConfigPath(projectRoot);
    }
  }

  let config: ResolvedConfig;

  if (configPath) {
    console.log(`📝 Loading config from: ${configPath}`);
    config = await loadConfig(configPath);
  } else {
    console.log('📝 No config file found, using defaults');
    const { resolveConfig } = await import('./config/loader.js');
    config = resolveConfig({});
  }

  console.log(`🔧 PalJS Generator v${GENERATOR_VERSION}`);
  console.log(`📁 Output: ${outputDir}`);

  // Write DMMF files
  console.log('📦 Writing DMMF...');
  const { jsonPath, tsPath } = writeDmmf(outputDir, dmmf);
  console.log(`   ✓ ${jsonPath}`);
  console.log(`   ✓ ${tsPath}`);

  // Generate types if enabled
  if (config.generateTypes) {
    console.log('📝 Generating types...');
    const typesPath = writeTypes({ outputDir, dmmf, config });
    console.log(`   ✓ ${typesPath}`);
  }

  // Generate GraphQL if enabled
  if (config.generateGraphQL && typeof config.generateGraphQL === 'object') {
    // Generate Nexus (server-side) if enabled
    if (config.generateGraphQL.nexus) {
      console.log('🔷 Generating Nexus GraphQL...');
      const nexusPaths = writeNexus({ outputDir, dmmf, config });
      console.log(`   ✓ Generated ${nexusPaths.length} Nexus files`);
    }

    // Generate client .graphql files if enabled
    if (config.generateGraphQL.client) {
      console.log('📄 Generating client GraphQL files...');
      const graphqlPaths = writeGraphQL({ outputDir, dmmf, config });
      console.log(`   ✓ Generated ${graphqlPaths.length} GraphQL files`);
    }
  }

  // Generate Admin if enabled
  if (config.generateAdmin && typeof config.generateAdmin === 'object' && config.generateAdmin.enabled) {
    console.log('🎛️  Generating Admin...');
    const adminPaths = writeAdmin({ outputDir, dmmf, config });
    console.log(`   ✓ Generated ${adminPaths.length} admin files`);
  }

  // Write main index.ts
  const indexContent = generateIndexFile(config);
  const { writeFileSync } = await import('node:fs');
  const indexPath = resolve(outputDir, 'index.ts');
  writeFileSync(indexPath, indexContent, 'utf-8');
  console.log(`   ✓ ${indexPath}`);

  console.log('✅ Generation complete!');
}

/**
 * Generate the main index.ts file
 */
function generateIndexFile(config: ResolvedConfig): string {
  const exports: string[] = [
    '// Generated by @paljs/generator - DO NOT EDIT',
    '',
    '// DMMF exports',
    "export { dmmf } from './dmmf/index.js';",
    "export type { DMMF } from '@prisma/generator-helper';",
  ];

  if (config.generateTypes) {
    exports.push('');
    exports.push('// Type exports for PrismaSelect');
    exports.push("export * from './types/index.js';");
  }

  if (config.generateGraphQL && typeof config.generateGraphQL === 'object' && config.generateGraphQL.nexus) {
    // Strip leading ./ from nexusOutput if present
    const nexusOutput = (config.generateGraphQL.nexusOutput || 'nexus').replace(/^\.\//, '');
    exports.push('');
    exports.push('// Nexus GraphQL exports');
    exports.push(`export * from './${nexusOutput}/index.js';`);
  }

  if (config.generateAdmin && typeof config.generateAdmin === 'object' && config.generateAdmin.enabled) {
    // Strip leading ./ from adminOutput if present
    const adminOutput = (config.generateAdmin.output || 'admin').replace(/^\.\//, '');
    exports.push('');
    exports.push('// Admin schema exports');
    exports.push(`export { default as adminSchema } from './${adminOutput}/schema.json' with { type: 'json' };`);
  }

  return exports.join('\n') + '\n';
}

// Start the generator
generatorHandler({
  onManifest,
  onGenerate,
});
